### ISSUE TITLE
NullReferenceException in Mac console app

### ISSUE THREAD

**Issue by joeshaw** [abock/conservatorio#4]
```
$ ./conservatorio thesaltmines
Conservatorio v1.2 (master/22b51cc, Tue Nov 24 03:10:10 UTC 2015)
  by Aaron Bockover (@abock)
  http://conservator.io

Starting work for 'thesaltmines'...
System.NullReferenceException: Object reference not set to an instance of an object
  at System.Net.ServicePointManager.FindServicePoint (System.Uri address, IWebProxy proxy) <0x16fdc38 + 0x00314> in <filename unknown>:0
  at System.Net.HttpWebRequest.GetServicePoint () <0x16fdb98 + 0x0004f> in <filename unknown>:0
  at System.Net.HttpWebRequest.get_ServicePoint () <0x16fdb70 + 0x00013> in <filename unknown>:0
  at (wrapper remoting-invoke-with-check) System.Net.HttpWebRequest:get_ServicePoint ()
  at System.Net.Http.HttpClientHandler.CreateWebRequest (System.Net.Http.HttpRequestMessage request) <0x16eaea0 + 0x001bb> in <filename unknown>:0
  at System.Net.Http.HttpClientHandler+<SendAsync>c__async0.MoveNext () <0x16e9d90 + 0x0015a> in <filename unknown>:0
```

(Many TaskAwaiter lines afterward omitted)

Doesn't seem to matter what username I use.  I'm on OS X 10.11.1.

**Comment by joeshaw** [comment]
Oh, I should point out that the Mac GUI app works fine.

**Comment by abock** [comment]
That smells of an mkbundle problem, which would explain why the GUI works. If you download the "Linux/Windows" console version, it's just the plain assembly, which you can use with system Mono. I'll look into mkbundle.

Thaaaaaanks!

**Comment by abock** [comment]
Hey @joeshaw, are you behind a proxy by any chance?

**Comment by abock** [comment]
@joeshaw mind testing this build? http://bock.io/~aaron/conservatorio

**Comment by joeshaw** [comment]
No proxies here.  Same error with that build, unfortunately.

**Comment by abock** [comment]
@joeshaw I've eliminated the separate Mac console app altogether. If you run the main binary inside the regular Mac app bundle from a shell, you'll get all the console goodness, yet still powered by NSURLSession, which is about 3x faster than the managed HTTP/SSL implementation in Mono.

This speedup is insane, especially for the Console version, where I am using `-f` to back up everyone I'm following on Rdio too. My collection went from taking 5 minutes, 40 seconds to taking 2 minutes 15 seconds.

`$ Conservatorio.app/Contents/MacOS/Conservatorio -help`

You need at least [Conservatorio 1.4](https://github.com/abock/conservatorio/releases/download/v1.4/Conservatorio.zip).

The GUI in the Mac app also now supports updating itself via Sparkle.

The magic sauce for the curious:
https://github.com/abock/conservatorio/blob/master/Conservatorio.Mac/Main.cs#L104

**Comment by joeshaw** [comment]
Thanks, worked great.
